name: sagapi_audio
description: Downloads and extracts arknights audio assets.
version: 1.0.0
environment:
  sdk: ^3.7.2

dependencies:
  archive: ^4.0.5
  collection: ^1.19.1
  http: ^1.3.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
