name: Download or update assets

on:
  workflow_dispatch: null
  schedule:
    - cron: "* 0,12 * * *"
  push:
    branches: [main]

concurrency:
  group: "${{ github.ref }}"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          dotnet: false
          large-packages: false
      - name: Remove all .NET versions
        run: |
          sudo apt-get remove --purge -y dotnet* || true
          sudo apt-get autoremove -y
          sudo rm -rf /usr/share/dotnet /etc/dotnet
      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dart sdk
        uses: dart-lang/setup-dart@v1
      - name: Prepare environment
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config http.postBuffer 2147483648
          if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then echo "FORCE=--force" >> $GITHUB_ENV; fi
          dart pub get
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Update assets
        run: dart run sagapi_audio ${{ env.FORCE }}
